export const courses = [
    {
        "name": "Reposteria",
        "coverPhoto": "https://picsum.photos/400/400",
        "url": "1",
        "summary": "Descubre el arte de la repostería y domina técnicas para preparar deliciosos postres.",
        "startHour": "18:00",
        "information": "Este curso enseña técnicas básicas de repostería, desde bizcochos hasta decoraciones con crema.",
        "what_will_you_learn": ["Preparar diferentes tipos de postres", "Decoración de postres"],
        "images": [
            "https://picsum.photos/500/500?random=1",
            "https://picsum.photos/500/500?random=2",
            "https://picsum.photos/500/500?random=3",
        ],
    },
    {
        "name": "Lenguaje de señas",
        "coverPhoto": "https://picsum.photos/400/400",
        "url": "2",
        "summary": "Aprende a comunicarte usando el lenguaje de señas universal para eliminar barreras de comunicación.",
        "startHour": "18:00",
        "information": "Curso diseñado para enseñar el lenguaje de señas universal con ejercicios prácticos.",
        "what_will_you_learn": ["El alfabeto en señas", "Comunicación básica en lenguaje de señas"],
        "images": [
            "https://picsum.photos/500/500?random=1",
            "https://picsum.photos/500/500?random=2",
            "https://picsum.photos/500/500?random=3",
        ],
    },
    {
        "name": "Corte y confección",
        "coverPhoto": "https://picsum.photos/400/400",
        "url": "3",
        "summary": "Aprende a diseñar y confeccionar prendas con tus propias manos.",
        "startHour": "18:00",
        "information": "Este curso enseña técnicas de corte y confección para elaborar prendas desde cero.",
        "what_will_you_learn": ["Patrones básicos de costura", "Confección de prendas simples"],
        "images": [
            "https://picsum.photos/500/500?random=1",
            "https://picsum.photos/500/500?random=2",
            "https://picsum.photos/500/500?random=3",
        ],
    },
    {
        "name": "Lecto-escritura",
        "coverPhoto": "https://picsum.photos/400/400",
        "url": "4",
        "summary": "Mejora tus habilidades de lectura y escritura, fundamentales para cualquier área del conocimiento.",
        "startHour": "18:00",
        "information": "Este curso fomenta el desarrollo de habilidades lecto-escriturales mediante ejercicios dinámicos.",
        "what_will_you_learn": ["Comprensión de textos", "Redacción efectiva"],
        "images": [
            "https://picsum.photos/500/500?random=1",
            "https://picsum.photos/500/500?random=2",
            "https://picsum.photos/500/500?random=3",
        ],
    },
    {
        "name": "Preparación de alimentos y bebidas",
        "coverPhoto": "https://picsum.photos/400/400",
        "url": "5",
        "summary": "Aprende a crear alimentos y bebidas únicas con técnicas sencillas y deliciosas.",
        "startHour": "18:00",
        "information": "Curso enfocado en la preparación de alimentos y bebidas con recetas innovadoras.",
        "what_will_you_learn": ["Mezclas de bebidas", "Preparación de aperitivos creativos"],
        "images": [
            "https://picsum.photos/500/500?random=1",
            "https://picsum.photos/500/500?random=2",
            "https://picsum.photos/500/500?random=3",
        ],
    },
];
