export const courses = [
    {
        "name": "Reposteria",
        "coverPhoto": "bakery_1.jpg",
        "url": "1",
        "summary": "Descubre el arte de la repostería y domina técnicas para preparar deliciosos postres.",
        "startHour": "18:00",
        "information": "Este curso enseña técnicas básicas de repostería, desde bizcochos hasta decoraciones con crema.",
        "what_will_you_learn": ["Preparar diferentes tipos de postres", "Decoración de postres"],
        "images": [
            "bakery_1.jpg",
            "bakery_2.jpg",
            "bakery_3.jpg",
        ],
    },
    {
        "name": "Lenguaje de señas",
        "coverPhoto": "sign_1.jpg",
        "url": "2",
        "summary": "Aprende a comunicarte usando el lenguaje de señas universal para eliminar barreras de comunicación.",
        "startHour": "18:00",
        "information": "Curso diseñado para enseñar el lenguaje de señas universal con ejercicios prácticos.",
        "what_will_you_learn": ["El alfabeto en señas", "Comunicación básica en lenguaje de señas"],
        "images": [
            "sign_1.jpg",
            "sign_2.jpg",
            "sign_3.jpg",
        ],
    },
    {
        "name": "Corte y confección",
        "coverPhoto": "tailoring_1.jpg",
        "url": "3",
        "summary": "Aprende a diseñar y confeccionar prendas con tus propias manos.",
        "startHour": "18:00",
        "information": "Este curso enseña técnicas de corte y confección para elaborar prendas desde cero.",
        "what_will_you_learn": ["Patrones básicos de costura", "Confección de prendas simples"],
        "images": [
            "tailoring_1.jpg",
            "tailoring_2.jpg",
            "tailoring_3.jpg",
        ],
    },
    {
        "name": "Lecto-escritura",
        "coverPhoto": "writing_1.jpg",
        "url": "4",
        "summary": "Mejora tus habilidades de lectura y escritura, fundamentales para cualquier área del conocimiento.",
        "startHour": "18:00",
        "information": "Este curso fomenta el desarrollo de habilidades lecto-escriturales mediante ejercicios dinámicos.",
        "what_will_you_learn": ["Comprensión de textos", "Redacción efectiva"],
        "images": [
            "writing_1.jpg",
            "writing_2.jpg",
            "writing_3.jpg",
        ],
    },
    {
        "name": "Preparación de alimentos y bebidas",
        "coverPhoto": "cooking_1.jpg",
        "url": "5",
        "summary": "Aprende a crear alimentos y bebidas únicas con técnicas sencillas y deliciosas.",
        "startHour": "18:00",
        "information": "Curso enfocado en la preparación de alimentos y bebidas con recetas innovadoras.",
        "what_will_you_learn": ["Mezclas de bebidas", "Preparación de aperitivos creativos"],
        "images": [
            "cooking_1.jpg",
            "cooking_2.jpg",
            "cooking_3.jpg",
        ],
    },
];
